# Project Info
# https://www.mkdocs.org/user-guide/configuration/#project-information
site_name: Fullchee's Notes
repo_url: https://github.com/Fullchee/notes
repo_name: Fullchee/notes
edit_uri: edit/main/docs/
site_description: My personal notes so that I can get things out of my head and into this system
site_author: Fullchee Zhang
copyright: Copyright &copy; 2022 Fullchee Zhang

# Navigation
# https://www.mkdocs.org/user-guide/configuration/#nav
# nav:
#   - Home: "../"
#   - "User Guide": "user-guide.md"
#   - "Bug Tracker": "/bugs/"

# Build
# https://www.mkdocs.org/user-guide/configuration/#build-directories
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  favicon: images/fullchee.png
  features:
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Preview Controls
# https://www.mkdocs.org/user-guide/configuration/#preview-controls
dev_addr: 127.0.0.1:5000

# Formatting options
# https://www.mkdocs.org/user-guide/configuration/#formatting-options

markdown_extensions:
  - abbr
  - admonition
  - attr_list # add attributes to html tags like height and width for images
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details # https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.magiclink
  - pymdownx.mark # highlighting: https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.tilde # https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      permalink: true

plugins:
  - git-revision-date
  - search
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  - tags:
      tags_file: tags.md

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-X95X8QVDWH
